### ISSUE TITLE
Python 2 vs 3 issues

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash-gitian#13]
With python 2 and 3 installed on the host system, I came across problems with ansible during the provision phase.

- Running the gitian build with python 3 does not appear to work.
- Running the gitian build with python 2, when ansible requires python 3 results in an error.
- Uninstalling and reinstalling ansible for python 2 (via pip2) and using virtualenv to ensure the gitian build runs with python 2 resolved the provisioning problems.

What have other engineers come across? Let's document and update README.

**Comment by arcalinea** [comment]
I've always used ansible in a virtualenv to manage python dependencies. Didn't run into any of these problems when I did the deterministic build this time, so it must be just on your local machine.

Where does ansible require python 3, giving you an error?
