### ISSUE TITLE
mac os instructions, brew command correction

### ISSUE THREAD

**Issue by superbaud** [zcash/zcash-gitian#133]
`brew install --cask ./vagrant.rb`

needs to be

`brew reinstall --cask ./vagrant.rb` otherwise it gives an error

**Comment by charlieok** [comment]
It's using an assumed starting point of a new laptop with no extra stuff installed, but of course steps can be adapted as needed to fit the situation.

<img width="634" alt="Screen Shot 2021-09-27 at 9 07 09 AM" src="https://user-images.githubusercontent.com/7226/134935275-bb72177c-14cb-4dc6-a1e7-decea8bc2b58.png">

**Comment by superbaud** [comment]
i did start with a clean brew install with nothing installed (having wiped the machine to downgrade it from a monterey macOS beta), it's just that when running all three commands:
```
$ curl -O -L https://github.com/Homebrew/homebrew-cask/raw/015bd57c9637d517f1a814e46a1ece5de570c263/Casks/vagrant.rb
$ brew install vagrant
$ brew install --cask ./vagrant.rb
``` 

as suggested in https://github.com/zcash/zcash-gitian/blob/master/dependency_install_steps_by_platform/macOS.md, the last command gives an error:
<img width="1116" alt="Screen Shot 2021-09-27 at 2 11 08 PM" src="https://user-images.githubusercontent.com/2592730/134970695-7d1d3f8b-c50e-4ea4-bfe6-743100eca7f0.png">

**Comment by charlieok** [comment]
oh, that's the mistake. I meant to replace `brew install vagrant`with `brew install --cask ./vagrant.rb`, not add a new command. Good catch again!

**Comment by superbaud** [comment]
Ohh ok! i just ran those three commands in order thinking that perhaps the install of vagrant from the repo was necessary to get the dependencies for the custom vagrant version! but if installing from the `vagrant.rb` works fine then there was no need!
