### ISSUE TITLE
Set-up relies on box https://atlas.hashicorp.com/debian/jessie64 which is now a 404

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash-gitian#16]
> The Packer, Artifact Registry and Terraform Enterprise (Legacy) features of Atlas will no longer be actively developed or maintained and will be fully decommissioned on Friday, March 30, 2018. Please see our guide on building immutable infrastructure with Packer on CI/CD for ideas on implementing Packer and Artifact Registry features yourself and the Upgrading From Terraform Enterprise (Legacy) guide to migrate to the new Terraform Enterprise.

**Comment by str4d** [comment]
See https://github.com/hashicorp/vagrant/issues/9442. The default URL was fixed in Vagrant 2.0.2, but the current Ubuntu LTS is on 1.9.1, and latest Ubuntu is only on 2.0.0.2. We should add the following to our Vagrantfile:

```
Vagrant::DEFAULT_SERVER_URL.replace('https://vagrantcloud.com')
```

That will resolve the issue for new users, but existing users will also need to run the following to correct their cached URL:

```
sed -i -- 's/atlas.hashicorp/vagrantcloud/g' ~/.vagrant.d/boxes/*/metadata_url
```

**Comment by bitcartel** [comment]
I saw the error because I was running Vagrant 2.0.2 aginst a cached debian/jessie64 box from previous builds.

**Comment by marsmensch** [comment]
@str4d Doesn't seem to be an issue anymore
```
==> zcash-build: Box 'debian/jessie64' could not be found. Attempting to find and install...
    zcash-build: Box Provider: virtualbox
    zcash-build: Box Version: >= 0
==> zcash-build: Loading metadata for box 'debian/jessie64'
    zcash-build: URL: https://vagrantcloud.com/debian/jessie64
==> zcash-build: Adding box 'debian/jessie64' (v8.11.0) for provider: virtualbox
    zcash-build: Downloading: https://vagrantcloud.com/debian/boxes/jessie64/versions/8.11.0/providers/virtualbox.box
    zcash-build: Download redirected to host: vagrantcloud-files-production.s3.amazonaws.com
==> zcash-build: Successfully added box 'debian/jessie64' (v8.11.0) for 'virtualbox'!
==> zcash-build: Importing base box 'debian/jessie64'...
```
