### ISSUE TITLE
Updating memory and cpu in Vagrantfile not reflected in gitian-build.sh

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash-gitian#24]
My Vagrantfile has this:
```
    gitian.vm.provider "virtualbox" do |v|
      v.name = "zcash-build"
      v.memory = 8192
      v.cpus = 4
    end
```
But inside the VM, gitian-build.sh remains as: https://github.com/zcash/zcash-gitian/blob/master/roles/gitian/templates/gitian-build.sh#L18

**Comment by str4d** [comment]
Until now, I've been applying the following diff (in addition to altering the Vagrantfile):

```diff
diff --git a/roles/gitian/templates/gitian-build.sh b/roles/gitian/templates/gitian-build.sh
index 99ed244..86451b2 100644
--- a/roles/gitian/templates/gitian-build.sh
+++ b/roles/gitian/templates/gitian-build.sh
@@ -15,8 +15,8 @@ SIGNER="{{ gpg_key_name }}"
 VERSION={{ zcash_version }}
 commit=false
 url={{ zcash_git_repo_url }}
-proc=2
-mem=3584
+proc=4
+mem=7584
 lxc=true
 scriptName=$(basename -- "$0")
 signProg="gpg2 --detach-sign"
```

**Comment by superbaud** [comment]
https://github.com/zcash/zcash-gitian/pull/146/commits/4dd31089142bd36caffb3a6a3fe61089587bc40b#diff-694acd8369decf276baf486a425784c7cb11405de69339a4a17bc672ea7c5cefR17-R18 will fix this
