### ISSUE TITLE
Vagrant file updated but build.sh was not

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash-gitian#3]
Set this:

```
    gitian.vm.provider "virtualbox" do |v|
      v.name = "zcash-build"
      v.memory = 8192
      v.cpus = 4
    end
```

But inside the image, build.sh shows:

```
proc=2
mem=3584
```

**Comment by ageis** [comment]
@bitcartel Those settings in gitian-build.sh are used by LXC (the build environment), and will not be affected by anything in Vagrantfile (the host environment). `gitian-build.sh` is provisioned through Ansible and those Vagrantfile mem, proc values are available as Ansible variables (yet). You're free to edit gitian-build.sh for your own purposes. I could also variable-ize them.
