### ISSUE TITLE
Set EDITOR to vi instead of nano

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash-gitian#5]

**Comment by nathan-at-least** [comment]
Uh oh… The editor wars have spilled over into zcashco!  ;-)   (I strongly prefer vi and detest nano, mainly due to muscle memory, but I know some others are the opposite.)

**Comment by ageis** [comment]
Resolved via https://github.com/zcash/zcash-gitian/commit/045836808941278d8ef5b3062dbe81ba188fa3df
