### ISSUE TITLE
FAILED! => {"changed": false, "failed": true, "msg": "parameters are mutually exclusive: ('copy', 'remote_src')"}

### ISSUE THREAD

**Issue by DATSEC** [zcash/zcash-gitian#8]
I need help

**@vagrant up --provision zcash-build**

Error

```
TASK [gitian : Download and extract VM builder source code.] *******************
fatal: [zcash-build]: FAILED! => {"changed": false, "failed": true, "msg": "parameters are mutually exclusive: ('copy', 'remote_src')"}

PLAY RECAP *********************************************************************
zcash-build                : ok=32   changed=24   unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

```

**Comment by DATSEC** [comment]
**Decision**

Now check the ansible version and confirm that it is successfully installed.

root@ansi:~# ansible --version
ansible 2.1.2

By default, you get the latest version (2.1.2 is when writing this post). If an older version is required for some reason, specify it in pip

sudo pip install ansible==2.1.2

**Comment by ageis** [comment]
@DATSEC Thanks for filing this issue. It's because the behavior of the unarchive module changed in Ansible 2.2. This was fixed in https://github.com/zcash/zcash-gitian/commit/d0ca504c06495fc5bb2e9f30760c1b50870e24f4.
